## NumPy Array Basics
### Creating Arrays

In [15]:
# 1D Array (Vector)
import numpy as np
arr_1 = np.array([2,3,4,5])
print(arr_1)
print(arr_1.ndim)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.dtype)

[2 3 4 5]
1
(4,)
4
int64


In [13]:
# 2D Array (Matrix)
arr_2 = np.array([[1,2,3], [4,5,6]])
print(arr_2)
print(arr_2.ndim)
print(arr_2.shape)
print(arr_2.size)
print(arr_2.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [16]:
# Type conversion
arr = np.array([1.1, 2.2, 3.3])
new_arr = arr.astype(int)
print(new_arr)

[1 2 3]


### Creating Arrays Using Functions

In [17]:
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [18]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [21]:
d = np.ones((3,4,2))
print(d)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:
d = np.full((2,3), 7)
print(d)

[[7 7 7]
 [7 7 7]]


In [23]:
a = np.arange(0, 10, 2)
print(a)  

[0 2 4 6 8]
