## NumPy Array Basics
### Creating Arrays

In [15]:
# 1D Array (Vector)
import numpy as np
arr_1 = np.array([2,3,4,5])
print(arr_1)
print(arr_1.ndim)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.dtype)

[2 3 4 5]
1
(4,)
4
int64


In [13]:
# 2D Array (Matrix)
arr_2 = np.array([[1,2,3], [4,5,6]])
print(arr_2)
print(arr_2.ndim)
print(arr_2.shape)
print(arr_2.size)
print(arr_2.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [16]:
# Type conversion
arr = np.array([1.1, 2.2, 3.3])
new_arr = arr.astype(int)
print(new_arr)

[1 2 3]
