## NumPy Array Basics
### Creating Arrays

In [15]:
# 1D Array (Vector)
import numpy as np
arr_1 = np.array([2,3,4,5])
print(arr_1)
print(arr_1.ndim)
print(arr_1.shape)
print(arr_1.size)
print(arr_1.dtype)

[2 3 4 5]
1
(4,)
4
int64


In [13]:
# 2D Array (Matrix)
arr_2 = np.array([[1,2,3], [4,5,6]])
print(arr_2)
print(arr_2.ndim)
print(arr_2.shape)
print(arr_2.size)
print(arr_2.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [16]:
# Type conversion
arr = np.array([1.1, 2.2, 3.3])
new_arr = arr.astype(int)
print(new_arr)

[1 2 3]


### Creating Arrays Using Functions

In [17]:
a = np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [18]:
b = np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
c = np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [21]:
d = np.ones((3,4,2))
print(d)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [22]:
d = np.full((2,3), 7)
print(d)

[[7 7 7]
 [7 7 7]]


In [23]:
a = np.arange(0, 10, 2)
print(a)  

[0 2 4 6 8]


In [24]:
a = np.linspace(0, 1, 5)
print(a)  

[0.   0.25 0.5  0.75 1.  ]


### Random Arrays in NumPy

In [25]:
import numpy as np

a = np.random.rand(5)  # 1D array
print(a)

b = np.random.rand(2, 3)  # 2x3 matrix
print(b)


[0.42927636 0.38335125 0.12942757 0.81017006 0.86249483]
[[0.54506815 0.38008093 0.67864165]
 [0.67717896 0.44304956 0.1047142 ]]


In [29]:
a = np.random.randint(1,10,size=5)
print(a)

[2 2 8 8 8]


In [30]:
b = np.random.randint(1,20,size=(2,3))
print(b)

[[10  4 13]
 [17 16  5]]


In [42]:
np.random.seed(7)
b = np.random.randint(1,20,size=(2,3))
print(b)

[[16  5  4]
 [ 8 15  9]]


In [43]:
np.random.seed(7)
x = np.random.randint(1,20,size=(2,3))
print(x)

[[16  5  4]
 [ 8 15  9]]


In [44]:
print(np.random.randn(5))  


[-0.15877062 -0.81377653  0.02006439 -0.34983013 -0.38108715]
